name: Release RetroS

permissions:
    contents: write

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.3

    - name: Test
      run: go test -v ./...

    - name: Build Go binary for Linux
      run: go build -o bin/linux/retros ./src

    - name: Build Go binary for OSX
      run: GOOS=darwin GOARCH=arm64 go build -o bin/mac/retros ./src

    - name: Build Go binary for Windows
      run: GOOS=windows go build -o bin/windows/retros.exe ./src

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/linux/retros
          bin/mac/retros
          bin/windows/retros.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release URL
      run: echo "Uploaded release to ${{ steps.create_release.outputs.upload_url }}"
